version: '3'

services:
  client:
    build: ./client
    ports:
      - '3000:3000'

  server:
    build: ./server
    ports:
      - '8080:8080'
    depends_on:
      - database

  database:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exam
    ports:
      - '3306:3306'
